/*
 * actions.c, generated by RTE VuGen on Wed Apr  6 14:38:29 2016
 */

/*
	PowerTerm for HP Performance Software for Windows 2000/XP/2003/Vista
	Version: 9.1.0
	Copyright (C) 1994-2007 ERICOM Software Ltd.
*/

Action1()
{
	/* *** The terminal type is 5250 Display. */
	TE_connect(
		"comm-type = tn5250;"
		"host-name = localhost;"
		"telnet-port = 9000;"
		"device-name = ;"
		"user-name = ;"
		"password = ;"
		"security-type = unsecured;"
		"terminal-type = 5250 display;"
		"terminal-model = 3477-fc;"
		"login-command-file = ;"
		"terminal-setup-file = ;"
		, 60000);
	if (TE_errno != TE_SUCCESS) 
		return -1;
	TE_wait_text("Sign On", 30, 1, 1, 80, 24, NULL, NULL, NULL);
	TE_disconnect();

	return 0;
} /* Action1() */


/* END OF FILE actions.c */
